spring:
  application:
    name: "MissioWorship"
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${MYSQL_URL:"unvalidURL"}
    username: ${MYSQL_USERNAME:"random"}
    password: ${MYSQL_PASSWORD:"password"}

missio:
  adminRole: "Admin"
  captcha:
    secret: ${CAPTCHA_SECRET:}
  jwt:
    secret: ${JWT_SECRET:}


