name: Pack and ship (Release)

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: missioworship
        settings-path: ${{ github.workspace }}

    - name: Get current version
      run: echo "cversion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build docker image
      run: docker build . --tag ${{secrets.DOCKER_USER}}/missio-backend:${{ env.cversion }} --tag ${{secrets.DOCKER_USER}}/missio-backend:dev

    - name: Docker push to repo
      run: docker push ${{secrets.DOCKER_USER}}/missio-backend --all-tags
