name: Pack and ship (Release)

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: missioworship
        settings-path: ${{ github.workspace }}
        
    - name: Get current version
      run: echo "cversion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: Compute new version
      id: bump_version
      uses: christian-draeger/increment-semantic-version@1.0.3
      with:
        current-version: ${{ env.cversion }}
        version-fragment: bug

    - name: Write new version
      run: mvn versions:set -DnewVersion=${{ steps.bump_version.outputs.next-version }} -DprocessAllModules=true

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        author_email: 'aaron@mbotton.com'
        author_name: 'Cloud Automation'
        message: 'chore: [auto] Update ${{ env.cversion }} image version to ${{ steps.bump_version.outputs.next-version }}'
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.ARTIFACT_UPLOAD_TOKEN }}
