name: On push

on:
  workflow_dispatch:
  pull_request:
    types: [ closed ]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: missioworship
          settings-path: ${{ github.workspace }}

      - name: Get current version
        run: echo "cversion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Compute new version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.3
        with:
          current-version: ${{ env.cversion }}
          version-fragment: bug

      - name: Write new version
        run: mvn versions:set -DnewVersion=${{ steps.bump_version.outputs.next-version }} -DprocessAllModules=true

      - name: Commit changes
        shell: bash
        run: |
          git config --global user.email "aaron@mbotton.com"
          git config --global user.name "Cloud Automation"
          git add pom.xml
          git commit -m 'chore: [auto] Update ${{ env.cversion }} image version to ${{ steps.bump_version.outputs.next-version }}'
          git push     

      - name: Create release with latest version
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: v${{ steps.bump_version.outputs.next-version }}
          name: v${{ steps.bump_version.outputs.next-version }}
          skipIfReleaseExists: true
          generateReleaseNotes: true
          makeLatest: true
          token: ${{ secrets.CI_PAT_TOKEN }}