name: Create a release

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: test
          name: Releasetes
          body: |
            Release created automatically by GitHub Actions.
          skipIfReleaseExists: true
          makeLatest: true
          token: ${{ secrets.CI_PAT_TOKEN }}